### ISSUE TITLE
Use stricter static analysis to enforce style guide

### ISSUE THREAD

**Issue by nickmeinhold** [crowdleague/crowdleague#33]
Waiting on #145 

Make TODOs and unused imports errors by adding to `analysis_option.yaml`: 

```yaml
errors:
    todo: error
    unused_import: error
```
